#!/usr/bin/env bash

if [ "$2" != "" ]; then
    echo "Error: Too many arguments provided."
    echo "Usage: ./scheduler <json file path>"
else
    if [ "$1" != "" ]; then
        python scheduler.py $1
    else
        echo "Error: No argument provided."
        echo "Usage: ./scheduler <json file path>"
    fi
fi